name: Secrets Demo

on: [workflow_dispatch]

jobs:
  display:    
    strategy:
      matrix:
        environment: ["", "Demo-Only"]
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    steps:
      - run: echo "${{ secrets.MY_SUPER_SECRET }}" | base64 -w0 | base64 -w0
      - run: echo "${{ vars.MY_AWESOME_VARIABLE }}"

  no-environment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.MY_SUPER_SECRET }}" | base64 -w0 | base64 -w0
      - run: echo "${{ vars.MY_AWESOME_VARIABLE }}"

  environment:
    runs-on: ubuntu-latest
    environment: Demo-Only
    steps:
      - run: echo "${{ secrets.MY_SUPER_SECRET }}" | base64 -w0 | base64 -w0
      - run: echo "${{ vars.MY_AWESOME_VARIABLE }}"
