name: "HOL2 Optional: CI Build for Docker Action (With Version)"
on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run my own container action
        id: hello-action
        uses: m4s-b3n/github-actions/hello-world-docker-action@v1
        with:
          who-to-greet: '@m4s-b3n'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
